project_id = "eoendveneygjkciuhfaw"

[functions.check-performance-alerts]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.generate-weekly-report]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-extract-companies]
verify_jwt = false